# WARNING!! This is to build from source

# to use a version that is prebuilt copy one of the entries from the examples folder!

version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: ohmyform
    port: 3000

services:

  redis:
    image: redis

  ohmyform:
    image: "${OHMYFORM_IMAGE}"
    environment:
      - CREATE_ADMIN=true
      - MAILER_URI=smtp://mail:1025
      - DATABASE_DRIVER=postgres
      - DATABASE_URL=postgresql://root:root@localhost:5432/ohmyform
      - LOGIN_NOTE=login with root:root!
      - SECRET_KEY=12345
    deploy:
      resources:
        limits:
          memory: 1000M
    # links:
    #   - db
    #   - redis
    #   - mail
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - db
    #   - redis

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  db:
    image: postgres:10-alpine
    volumes:
      - PG_VOLUME:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ohmyform

volumes:
  PG_VOLUME:
