# WARNING!! This is to build from source

# to use a version that is prebuilt copy one of the entries from the examples folder!

version: '3'

# uffizzi integration
x-uffizzi:
  ingress:
    service: ui
    port: 8080

services:
  redis:
    image: redis
  db:
    image: postgres:10-alpine
    volumes:
      - PG_VOLUME:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ohmyform
    restart: unless-stopped
  ui:
    image: "${OHMYFORM_UI_IMAGE}"
    environment:
      ENDPOINT: http://localhost:8090/graphql
      SERVER_ENDPOINT: http://api:5000/graphql
      PORT: 5000
    ports:
      - "8080:5000"
    restart: unless-stopped
  api:
    image: "{OHMYFORM_API_IMAGE}"
    environment:
      CREATE_ADMIN: "true"
      ADMIN_EMAIL: admin@local.host
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgresql://root:root@db:5432/ohmyform
      MAILER_URI: smtp://local.host
      REDIS_URL: redis://redis
      PORT: 5000
    ports:
      - "8090:5000"

volumes:
   PG_VOLUME:


# services:

#   redis:
#     image: redis

#   ohmyform:
#     image: "${OHMYFORM_IMAGE}"
#     environment:
#       CREATE_ADMIN: "TRUE"
#       ADMIN_EMAIL: admin@local.host
#       ADMIN_USERNAME: admin
#       ADMIN_PASSWORD: admin
#       DATABASE_DRIVER: postgres
#       DATABASE_URL: "postgresql://root:root@localhost:5432/ohmyform"
#       MAILER_URI: smtp://mail:1025
#       LOGIN_NOTE: "Either login with admin:admin or create your own account to test OhMyForm"
#     ports:
#       - "8080:3000"
#     # environment:
#     #   - CREATE_ADMIN=true
#     #   - MAILER_URI=smtp://mail:1025
#     #   - DATABASE_DRIVER=postgres
#     #   - DATABASE_URL=postgresql://root:root@localhost:5432/ohmyform
#     #   - LOGIN_NOTE=login with root:root!
#     #   - SECRET_KEY=12345
#     deploy:
#       resources:
#         limits:
#           memory: 1000M
#     # links:
#     #   - db
#     #   - redis
#     #   - mail
#     # ports:
#     #   - "3000:3000"
#     # depends_on:
#     #   - db
#     #   - redis

#   mail:
#     image: mailhog/mailhog
#     ports:
#       - "8025:8025"

#   db:
#     image: postgres:10-alpine
#     volumes:
#       - PG_VOLUME:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_USER=root
#       - POSTGRES_PASSWORD=root
#       - POSTGRES_DB=ohmyform

# volumes:
#   PG_VOLUME:
